/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos de CADIHOL
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../fetch";
export type GetWorkoutPlansParams = {
  active?: GetWorkoutPlansActive;
};

export type GetWorkoutPlansActive =
  (typeof GetWorkoutPlansActive)[keyof typeof GetWorkoutPlansActive];

export const GetWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlans500 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansBodyWorkoutDaysItemWeekDay =
  (typeof PostWorkoutPlansBodyWorkoutDaysItemWeekDay)[keyof typeof PostWorkoutPlansBodyWorkoutDaysItemWeekDay];

export const PostWorkoutPlansBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type PostWorkoutPlansBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type PostWorkoutPlansBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: PostWorkoutPlansBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: PostWorkoutPlansBodyWorkoutDaysItemExercisesItem[];
};

export type PostWorkoutPlansBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: PostWorkoutPlansBodyWorkoutDaysItem[];
};

export type PostWorkoutPlans201WorkoutDaysItemWeekDay =
  (typeof PostWorkoutPlans201WorkoutDaysItemWeekDay)[keyof typeof PostWorkoutPlans201WorkoutDaysItemWeekDay];

export const PostWorkoutPlans201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type PostWorkoutPlans201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type PostWorkoutPlans201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: PostWorkoutPlans201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: PostWorkoutPlans201WorkoutDaysItemExercisesItem[];
};

export type PostWorkoutPlans201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: PostWorkoutPlans201WorkoutDaysItem[];
};

export type PostWorkoutPlans400 = {
  error: string;
  code: string;
};

export type PostWorkoutPlans401 = {
  error: string;
  code: string;
};

export type PostWorkoutPlans404 = {
  error: string;
  code: string;
};

export type PostWorkoutPlans500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay];

export const GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlansWorkoutPlanId200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlansWorkoutPlanId200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlansWorkoutPlanId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlansWorkoutPlanId200WorkoutDaysItem[];
};

export type GetWorkoutPlansWorkoutPlanId401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanId404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanId500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay =
  (typeof GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay)[keyof typeof GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay];

export const GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200WeekDay;
  exercises: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200ExercisesItem[];
  sessions: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200SessionsItem[];
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId500 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions401 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions404 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions409 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions422 = {
  error: string;
  code: string;
};

export type PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions500 = {
  error: string;
  code: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId200 =
  {
    /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
    id: string;
    /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
    startedAt: string;
    /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
    completedAt: string;
  };

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId401 =
  {
    error: string;
    code: string;
  };

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId404 =
  {
    error: string;
    code: string;
  };

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId500 =
  {
    error: string;
    code: string;
  };

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 1 */
  weightInGrams: number;
  /** @minimum 1 */
  heightInCentimeters: number;
  /** @minimum 1 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type ChatWithAIBody = {
  messages: unknown[];
};

export type ChatWithAI401 = {
  error: string;
  code: string;
};

export type ChatWithAI500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary List Workout Plans
 */
export type getWorkoutPlansResponse200 = {
  data: GetWorkoutPlans200Item[];
  status: 200;
};

export type getWorkoutPlansResponse401 = {
  data: GetWorkoutPlans401;
  status: 401;
};

export type getWorkoutPlansResponse500 = {
  data: GetWorkoutPlans500;
  status: 500;
};

export type getWorkoutPlansResponseSuccess = getWorkoutPlansResponse200 & {
  headers: Headers;
};
export type getWorkoutPlansResponseError = (
  | getWorkoutPlansResponse401
  | getWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansResponse =
  | getWorkoutPlansResponseSuccess
  | getWorkoutPlansResponseError;

export const getGetWorkoutPlansUrl = (params?: GetWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const getWorkoutPlans = async (
  params?: GetWorkoutPlansParams,
  options?: RequestInit,
): Promise<getWorkoutPlansResponse> => {
  return customFetch<getWorkoutPlansResponse>(getGetWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create Workout Plan
 */
export type postWorkoutPlansResponse201 = {
  data: PostWorkoutPlans201;
  status: 201;
};

export type postWorkoutPlansResponse400 = {
  data: PostWorkoutPlans400;
  status: 400;
};

export type postWorkoutPlansResponse401 = {
  data: PostWorkoutPlans401;
  status: 401;
};

export type postWorkoutPlansResponse404 = {
  data: PostWorkoutPlans404;
  status: 404;
};

export type postWorkoutPlansResponse500 = {
  data: PostWorkoutPlans500;
  status: 500;
};

export type postWorkoutPlansResponseSuccess = postWorkoutPlansResponse201 & {
  headers: Headers;
};
export type postWorkoutPlansResponseError = (
  | postWorkoutPlansResponse400
  | postWorkoutPlansResponse401
  | postWorkoutPlansResponse404
  | postWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type postWorkoutPlansResponse =
  | postWorkoutPlansResponseSuccess
  | postWorkoutPlansResponseError;

export const getPostWorkoutPlansUrl = () => {
  return `/workout-plans/`;
};

export const postWorkoutPlans = async (
  postWorkoutPlansBody: PostWorkoutPlansBody,
  options?: RequestInit,
): Promise<postWorkoutPlansResponse> => {
  return customFetch<postWorkoutPlansResponse>(getPostWorkoutPlansUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postWorkoutPlansBody),
  });
};

/**
 * @summary Get a Workout Plan
 */
export type getWorkoutPlansWorkoutPlanIdResponse200 = {
  data: GetWorkoutPlansWorkoutPlanId200;
  status: 200;
};

export type getWorkoutPlansWorkoutPlanIdResponse401 = {
  data: GetWorkoutPlansWorkoutPlanId401;
  status: 401;
};

export type getWorkoutPlansWorkoutPlanIdResponse404 = {
  data: GetWorkoutPlansWorkoutPlanId404;
  status: 404;
};

export type getWorkoutPlansWorkoutPlanIdResponse500 = {
  data: GetWorkoutPlansWorkoutPlanId500;
  status: 500;
};

export type getWorkoutPlansWorkoutPlanIdResponseSuccess =
  getWorkoutPlansWorkoutPlanIdResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlansWorkoutPlanIdResponseError = (
  | getWorkoutPlansWorkoutPlanIdResponse401
  | getWorkoutPlansWorkoutPlanIdResponse404
  | getWorkoutPlansWorkoutPlanIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansWorkoutPlanIdResponse =
  | getWorkoutPlansWorkoutPlanIdResponseSuccess
  | getWorkoutPlansWorkoutPlanIdResponseError;

export const getGetWorkoutPlansWorkoutPlanIdUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlansWorkoutPlanId = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlansWorkoutPlanIdResponse> => {
  return customFetch<getWorkoutPlansWorkoutPlanIdResponse>(
    getGetWorkoutPlansWorkoutPlanIdUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get a Workout Day
 */
export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse200 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId200;
  status: 200;
};

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse401 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId401;
  status: 401;
};

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse404 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId404;
  status: 404;
};

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse500 = {
  data: GetWorkoutPlansWorkoutPlanIdDaysWorkoutDayId500;
  status: 500;
};

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseSuccess =
  getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseError = (
  | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse401
  | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse404
  | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse =
  | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseSuccess
  | getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponseError;

export const getGetWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutPlansWorkoutPlanIdDaysWorkoutDayId = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse> => {
  return customFetch<getWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdResponse>(
    getGetWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdUrl(
      workoutPlanId,
      workoutDayId,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a Workout Session
 */
export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse201 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions201;
  status: 201;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse401 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions401;
  status: 401;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse404 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions404;
  status: 404;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse409 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions409;
  status: 409;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse422 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions422;
  status: 422;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse500 = {
  data: PostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions500;
  status: 500;
};

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseSuccess =
  postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse201 & {
    headers: Headers;
  };
export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseError =
  (
    | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse401
    | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse404
    | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse409
    | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse422
    | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse500
  ) & {
    headers: Headers;
  };

export type postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse =
  | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseSuccess
  | postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponseError;

export const getPostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessions = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse> => {
  return customFetch<postWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsResponse>(
    getPostWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsUrl(
      workoutPlanId,
      workoutDayId,
    ),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a Workout Session
 */
export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse200 =
  {
    data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId200;
    status: 200;
  };

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse401 =
  {
    data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId401;
    status: 401;
  };

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse404 =
  {
    data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId404;
    status: 404;
  };

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse500 =
  {
    data: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId500;
    status: 500;
  };

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseSuccess =
  patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse200 & {
    headers: Headers;
  };
export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseError =
  (
    | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse401
    | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse404
    | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse500
  ) & {
    headers: Headers;
  };

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse =

    | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseSuccess
    | patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponseError;

export const getPatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdUrl =
  (workoutPlanId: string, workoutDayId: string, sessionId: string) => {
    return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
  };

export const patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionId =
  async (
    workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,
    options?: RequestInit,
  ): Promise<patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse> => {
    return customFetch<patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdResponse>(
      getPatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdSessionsSessionIdUrl(
        workoutPlanId,
        workoutDayId,
        sessionId,
      ),
      {
        ...options,
        method: "PATCH",
      },
    );
  };

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get workout statistics
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user train data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me/`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me/`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type chatWithAIResponse401 = {
  data: ChatWithAI401;
  status: 401;
};

export type chatWithAIResponse500 = {
  data: ChatWithAI500;
  status: 500;
};
export type chatWithAIResponseError = (
  | chatWithAIResponse401
  | chatWithAIResponse500
) & {
  headers: Headers;
};

export type chatWithAIResponse = chatWithAIResponseError;

export const getChatWithAIUrl = () => {
  return `/ai/`;
};

export const chatWithAI = async (
  chatWithAIBody: ChatWithAIBody,
  options?: RequestInit,
): Promise<chatWithAIResponse> => {
  return customFetch<chatWithAIResponse>(getChatWithAIUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chatWithAIBody),
  });
};

/**
 * Hello World
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
